# Generated by Django 3.0.7 on 2020-10-14 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20201013_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='alexnet_prediction',
        ),
        migrations.RemoveField(
            model_name='image',
            name='backprop_alexnet_image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='gradcam_alexnet_image',
        ),
        migrations.RemoveField(
            model_name='image',
            name='squadcam_alexnet_image',
        ),
        migrations.AlterField(
            model_name='answer',
            name='model',
            field=models.CharField(choices=[('vgg', 'vgg'), ('resnet', 'resnet')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='modelA',
            field=models.CharField(choices=[('vgg', 'vgg'), ('resnet', 'resnet')], max_length=200),
        ),
        migrations.AlterField(
            model_name='comparison',
            name='modelB',
            field=models.CharField(choices=[('vgg', 'vgg'), ('resnet', 'resnet')], max_length=200),
        ),
    ]
