# Generated by Django 3.1.2 on 2020-10-14 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20201014_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.prediction'),
        ),
        migrations.AlterField(
            model_name='image',
            name='choice_one',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice_one', to='polls.prediction'),
        ),
        migrations.AlterField(
            model_name='image',
            name='choice_two',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choice_two', to='polls.prediction'),
        ),
        migrations.AlterField(
            model_name='image',
            name='resnet_prediction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resnet_prediction', to='polls.prediction'),
        ),
        migrations.AlterField(
            model_name='image',
            name='true_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='true_label', to='polls.prediction'),
        ),
        migrations.AlterField(
            model_name='image',
            name='vgg_prediction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vgg_prediction', to='polls.prediction'),
        ),
    ]
