# Generated by Django 3.1.2 on 2020-10-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_auto_20201014_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prediction',
            name='prediction',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
